language: generic 
sudo: required 
services:
  - docker

before_install:
  - docker build -t takkarharsh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true takkarharsh/docker-react npm run test